### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by yCobanoglu** [ElectronicBabylonianLiterature/ebl-frontend#19]
Why?

_Originally posted by @jlaasonen in https://github.com/ElectronicBabylonianLiterature/ebl-frontend/pull/17_

This was an old commit. I merged it with thin-rulings it is fixed now.
I can't answer to your conversation directly. I don't know why exactly maybe because it's outdated.

**Comment by jlaasonen** [comment]
Why did you merge with an another branch? Now there is obsolete code in #17 which does not belong there and will most likely conflict with the final implementation in #10.  The branch cannot be merged before it is removed.

**Comment by jlaasonen** [comment]
See #18.
