### ISSUE TITLE
Is eBL publicly available now?

### ISSUE THREAD

**Issue by wpzdm** [ElectronicBabylonianLiterature/ebl-frontend#288]
Hi,

I guess this is not the right place to ask but I cannot find a better one.

I am introduced to your project by Sophus Helle's new translation of Gilgamesh, where it is mentioned that this project is publicly available and people can find new segments and translations.
But it seems the website ebl.lmu.de is not for public registration now. Is it?

I am considering being a tester in exchange to have access to the literature. I am a soon-to-be postdoc in statistics and machine learning and a former full-time programmer, so my experience might be helpful.

Thank you,
Abel

**Comment by ejimsan** [comment]
Dear Abel,

Thank you for your email. We would be happy to create a user for you. Please send me an email.

With best wishes,

Enrique

**Comment by wpzdm** [comment]
Dear Enrique,

Sorry for this super late reply...
Some personal things overloaded me later, and I recall your project and this communication recently.

I have sent you an email with details.

Best wishes,
Abel
