### ISSUE TITLE
In-text citations on public pages require authentication

### ISSUE THREAD

**Issue by larsgw** [ElectronicBabylonianLiterature/ebl-frontend#336]
E.g. on https://www.ebl.lmu.de/about the in-text citations show up in red as `@bib{<code>@<page>}`. There are 33 of these in-text citations, and I am getting 33 messages like "Error: Login required" in the console.

**Comment by khoidt** [comment]
Hi @larsgw, I'm glad to see you here and thanks for noticing. We are aware of this issue. It has to do with guest permissions and will disappear tomorrow shortly before the official launch workshop when guest access to the data will be opened.
